# Generated by Django 4.1.4 on 2023-02-27 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_15', '0002_rename_image_catsample_catimage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prdsample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prd_image', models.ImageField(upload_to='simple')),
                ('prd_name', models.IntegerField()),
            ],
        ),
    ]
