# Generated by Django 4.1.4 on 2023-02-27 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_15', '0003_prdsample'),
    ]

    operations = [
        migrations.RenameField(
            model_name='catsample',
            old_name='catname',
            new_name='cat_name',
        ),
        migrations.RemoveField(
            model_name='catsample',
            name='catimage',
        ),
        migrations.AddField(
            model_name='catsample',
            name='cat_image',
            field=models.ImageField(default='null.jpg', upload_to='sample'),
        ),
        migrations.AddField(
            model_name='prdsample',
            name='prd_cat',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='prdsample',
            name='prd_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='prdsample',
            name='prd_image',
            field=models.ImageField(default='null.jpg', upload_to='simple'),
        ),
        migrations.AlterField(
            model_name='prdsample',
            name='prd_name',
            field=models.CharField(max_length=10),
        ),
    ]
